---
title: "A short article as a placeholder. In development."
description: |
  This is also a simple description to fullfill the space and see what a real
  article would look like.
categories:
  - portfolios
  - dygraphs
author:
  - name: Joaquin Casino
    url: https://github.com/jcasinods
date: 03-14-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(ggplot2)
library(data.table)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

```{r simple_plot, preview = TRUE}
data <- data.table(
  variable = LETTERS,
  value    = seq(0, 1, 1 / length(LETTERS))[2:(length(LETTERS) + 1)]
)

ggplot(data, aes(x = variable, y = value, fill = value)) +
  geom_col(width = 1.2, position = "identity") +
  coord_polar(theta = "y") +
  theme_void() +
  scale_fill_distiller(palette = "YlOrRd") +
  guides(
    fill = guide_colorsteps(barwidth = 10,
                            barheight = 0.4,
                            title = NULL,
                            label = FALSE)
  ) +
  theme(
    legend.position = "bottom"
  )
```